
default:
  use: true
  skin: "example"
  
#데미지 표시의 효과입니다.
#  “spin” -> 데미지 표시가 회전합니다.
#  “bound” -> 데미지 표시가 위 아래로 이동합니다.
#  “basic” -> 기본값입니다.
indicate-effect: "basic"

#데미지 표시가 생성되는 범위를 설정합니다.
indicate-region: 1

#데미지 표시의 지속 시간입니다.
indicate-duration: 2

#데미지 표시 숫자 앞에 붙는 접두사입니다.
indicate-prefix: ' + '

#데미지 표시의 스킨입니다, 커스텀 폰트로 설정하면 됩니다.
indicate-skin:
  use: false
  skin:
    "0": ""
    "1": ""
    "2": ""
    "3": ""
    "4": ""
    "5": ""
    "6": ""
    "7": ""
    "8": ""
    "9": ""
    dot: ""